<footer style="position: fixed; bottom: 0; left: 0; width: 100%; background-color: #f8f9fa; padding: 10px;">
    <div style="display: flex; justify-content: center; align-items: center; height: 100%;">
        @auth
            @php
                $user = Auth::user();
                $userSignature = app('App\Http\Controllers\SignatureController')->userSignatureByEmployeeId($user->id);
                $documentId = session('documentID', '');

                $qrText =
                    'Report generated by ' .
                    $user->userFullName .
                    ' - ' .
                    $user->getRoleNameAttribute() .
                    ($userSignature ? ' (' . $userSignature->unique_signature . ')' : '') .
                    ' at ' .
                    now()->format('j M Y H:i:s') .
                    ($documentId ? ' Document ID: ' . $documentId : '');

                // Default text when no signature exists
                $qrFallbackText =
                    'Report printed at ' . now()->format('j M Y H:i:s') . ' by ' . $user->userFullName . '.';
            @endphp

            <div class="qrcode">
                <p style="margin: 0;">{{ $qrFallbackText }}</p>
            </div>
        {{-- <div class="qrcode" style="position: fixed; bottom: 15px; left: 20px;">
                <img src="data:image/png;base64,{{ DNS2D::getBarcodePNG($userSignature ? $qrText : $qrFallbackText, 'QRCODE', 3, 3, [39, 48, 54]) }}"
                    style="width: 70px;">
            </div> --}} @endauth
    </div>
</footer>
