<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sample Test Report</title>
    <link rel="stylesheet" href="{{ asset('css/sampletestCSS.css') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap5.css') }}">

</head>

<body style="font-family: 'Helvetica, Arial, sans-serif'">

    <div class="container header">
        <div class="row mt-5">
            <div class="col-md-2">
                <img src="{{ asset('img/paklogo4.png') }}" class="w-100" alt="" srcset="">
            </div>
            <div class="col-md-8">
                <h4 style="font-weight: bold;">ARMED FORCES MEDICAL STORES LABORATORY</h4>
                <hr>
                <h5 style="font-weight: bold;">Supply Samples Details</h5>


            </div>
            <div class="col-md-2">
                <img src="{{ asset('img/AFMS LOGO-01.png') }}" class="w-100" alt="" srcset="">

            </div>
        </div>
    </div>

    <div class="container-fluid mb-5">

        <table class="table table-bordered" id="allTran" style="font-size: 12px;">
            <thead class="text-center">
                <tr>
                    <th>Date</th>
                    <th colspan="1" id="dateCell">{{ \Carbon\Carbon::now()->format('d:m:Y') }}</th>
                    <th colspan="7"></th>
                    <th colspan="4"><b>Generated By:</b><label style="font-weight: 500;">Room AFML</label></th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td colspan="2" rowspan="2"></td>
                    <!-- Generating columns dynamically with a loop -->
                    <script>
                        for (let i = 1; i <= 4; i++) {
                            document.write(`<td colspan="2" >${i} Insti</td>`);
                        }
                    </script>
                    <td colspan="2">Total</td>
                </tr>

                <tr>
                    <?php for($i = 0; $i < 5; $i++): ?>
                    <td class="sample">Sample</td>
                    <td class="batch">Batch</td>
                    <?php endfor; ?>
                </tr>

                <tr>
                    <td rowspan="4">Total No. Of Samples</td>
                </tr>

                <tr>
                    <td>Received from AFIMS</td>
                    <td>{{ $ReceivedSampleInst1 }}</td>
                    <td>{{ $ReceivedBatchInst1 }}</td>
                    <td>{{ $ReceivedSampleInst2 }}</td>
                    <td>{{ $ReceivedBatchInst2 }}</td>
                    <td>{{ $ReceivedSampleInst3 }}</td>
                    <td>{{ $ReceivedBatchInst3 }}</td>
                    <td>{{ $ReceivedSampleInst4 }}</td>
                    <td>{{ $ReceivedBatchInst4 }}</td>
                    <td>{{ $TotalReceivedSamples }}</td>
                    <td>{{ $TotalReceivedBatchs }}</td>
                </tr>
                <tr>
                    <td>STR Fwd to AFIMS</td>

                    <td>{{ $str1 }}</td>
                    <td>{{ $strbatch1 }}</td>
                    <td>{{ $str2 }}</td>
                    <td>{{ $strbatch2 }}</td>
                    <td>{{ $str3 }}</td>
                    <td>{{ $strbatch3 }}</td>
                    <td>{{ $str4 }}</td>
                    <td>{{ $strbatch4 }}</td>
                    <td>{{ $TotalSTRSamples }}</td>
                    <td>{{ $TotalSTRBatchs }}</td>

                </tr>
                <tr>
                    <td>Total Pending</td>


                    <td>{{ abs($TRSTRI1) }}</td>
                    <td>{{ abs($TRBSTRI1) }}</td>
                    <td>{{ abs($TRSTRI2) }}</td>
                    <td>{{ abs($TRBSTRI2) }}</td>
                    <td>{{ abs($TRSTRI3) }}</td>
                    <td>{{ abs($TRBSTRI3) }}</td>
                    <td>{{ abs($TRSTRI4) }}</td>
                    <td>{{ abs($TRBSTRI4) }}</td>
                    <td>{{ abs($totalSamplePending) }}</td>
                    <td>{{ abs($totalBatchPending) }}</td>

                </tr>
            </tbody>

        </table>
        <div class="row mt-5">
            <div class="col-md-12">
                <h4 style="text-decoration: underline;"><b>Tender Samples Details</b></h4>
            </div>
            <div class="col-md-12">
                <table class="table table-bordered" id="allTran" style="font-size: 12px;;font-weight:bold">
                    <thead class="text-center">
                    </thead>
                    <tbody>

                        <tr>
                            <td colspan="2"></td>
                            <td>T/E</td>
                            <td>Firms/Batches</td>

                        </tr>
                        <tr>
                            <td rowspan="4">Total No. Of Samples</td>
                        </tr>

                        <tr>
                            <td>Received from AFIMS</td>
                            <td>{{ $TotalReceivedSamples }}</td>
                            <td>{{ $TotalReceivedBatchs }}</td>

                        </tr>
                        <tr>
                            <td>STR Fwd to AFIMS</td>
                            <td>{{ $TotalSTRSamples }}</td>
                            <td>{{ $TotalSTRBatchs }}</td>
                        </tr>
                        <tr>
                            <td>Total Pending</td>
                            <td>{{ abs($totalSamplePending) }}</td>
                            <td>{{ abs($totalBatchPending) }}</td>
                        </tr>
                    </tbody>

                </table>
            </div>
        </div>
    </div>
    {{-- @include('footer') --}}

</body>

</html>
