@extends('layouts.app')
@section('title', __('report.Sample Report'))
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
@section('content')

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="form-group" style="margin-top: -4%;">
                <h3>{{ __('home.sample_state') }}</h3>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="form-group pull-right">
                 <div class="input-group">
                    <a href="{{ url('pdf-sample-report') }}" class="btn btn-info" id="pdfURL">
                        view
                    </a> 
                    
                    {{-- &nbsp;&nbsp;&nbsp; --}}
                    {{-- <button type="button" class="btn btn-primary" id="dashboard_date_filter">
                        <span>
                            <i class="fa fa-calendar"></i> {{ __('messages.filter_by_date') }}
                        </span>
                        <i class="fa fa-caret-down"></i>
                    </button>
                     --}}
                </div>
            </div>
        </div>
    </div>
    @component('components.dashbord_widget', ['class' => 'box-primary'])
        
    <table class="table" id="allTran" border="2px solid black" style="text-align: center">
        <thead class="text-center">
            <tr>
                <th colspan="14" style="border: 2px solid black; text-align: center;">Supply Samples Details</th>
            </tr>
            <tr>
                <th style="border: 2px solid black; text-align: center;">Date</th>
                <th colspan="1" style="border: 2px solid black; text-align: center;" id="dateCell">{{ \Carbon\Carbon::now()->format('d:m:Y') }}</th>
                <th colspan="7"style="border: 2px solid black; text-align: center;"></th>
                <th colspan="4" style="border: 2px solid black; text-align: center;"><b>Generated By:</b><label style="font-weight: 500;">Room AFML</label></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td colspan="2" rowspan="2" style="border: 2px solid black; text-align: center;"></td>
                <!-- Generating columns dynamically with a loop -->
                <script>
                    for (let i = 1; i <= 4; i++) {
                        document.write(`<td colspan="2" style="border: 2px solid black; text-align: center;">${i} Insti</td>`);
                    }
                </script>
                <td colspan="2" style="border: 2px solid black; text-align: center;">Total</td>
            </tr>
            
            <tr>
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
            </tr>
            <tr>
                <td rowspan="4" style="border: 2px solid black; text-align: center;">Total No. Of Samples</td>
            </tr>

            <tr>
                <td style="border: 2px solid black; text-align: center;">Received from AFIMS</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSampleInst1 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedBatchInst1 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSampleInst2 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedBatchInst2 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSampleInst3 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedBatchInst3 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSampleInst4 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedBatchInst4 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $TotalReceivedSamples }}</td>
                <td style="border: 2px solid black; text-align: center;"">{{ $TotalReceivedBatchs }}</td>
            </tr>
            <tr>
                <td style="border: 2px solid black; text-align: center;">STR Fwd to AFIMS</td>
              
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRSample1 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRBatch1 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRSample2 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRBatch2 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRSample3 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRBatch3 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRSample4 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $ReceivedSTRBatch4 }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ $TotalSTRSamples }}</td>
                <td style="border: 2px solid black; text-align: center;"">{{ $TotalSTRBatchs }}</td>

            </tr>
            <tr>
                <td style="border: 2px solid black; text-align: center;">Total Pending</td>
               
              
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRSTRI1) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRBSTRI1) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRSTRI2) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRBSTRI2) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRSTRI3) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRBSTRI3) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRSTRI4) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($TRBSTRI4) }}</td>
                <td style="border: 2px solid black; text-align: center;">{{ abs($totalSamplePending) }}</td>
                <td style="border: 2px solid black; text-align: center;"">{{ abs($totalBatchPending) }}</td>

            </tr>
        </tbody>

    </table>
    {{-- <table class="table" id="dateTran" border="2px solid black"  style="text-align: center; display: none">
        <thead class="text-center">
            <tr>
                <th colspan="14" style="border: 2px solid black; text-align: center;">Supply Samples Details</th>
            </tr>
            <tr id="dataHeading">
            </tr>
        </thead>
        <tbody>
    
            <tr>
                <td colspan="2" rowspan="2" style="border: 2px solid black; text-align: center;"></td>
                <!-- Generating columns dynamically with a loop -->
                <script>
                    for (let i = 1; i <= 4; i++) {
                        document.write(`<td colspan="2" style="border: 2px solid black; text-align: center;">${i} Insti</td>`);
                    }
                </script>
                <td colspan="2" style="border: 2px solid black; text-align: center;">Total</td>
            </tr>
            
            <tr>
                <!-- Generating Sample and Batch columns dynamically with a loop -->
                <script>
                    for (let i = 1; i <= 4; i++) {
                        document.write(`<td style="border: 2px solid black; text-align: center;">Sample</td>`);
                        document.write(`<td style="border: 2px solid black; text-align: center;">Batch</td>`);
                    }
                </script>
                
                <td style="border: 2px solid black; text-align: center;">Sample</td>
                <td style="border: 2px solid black; text-align: center;">Batch</td>
            </tr>
            <tr>
                <td rowspan="4" style="border: 2px solid black; text-align: center;">Total No. Of Samples</td>
            </tr>
    
            <tr id="recived">
               
            </tr>
            <tr>
                <td style="border: 2px solid black; text-align: center;">STR Fwd to AFIMS</td>
                @php
                    $totalSampleSTR = 0;
                    $totalBatchSTR = 0;
                @endphp
                @for ($i = 1; $i <= 4; $i++)
                    <td style="border: 2px solid black; text-align: center;">{{ $strFwdToAFIMS[$i] }}</td>
                    <td style="border: 2px solid black; text-align: center;">{{ $strFwdToAFIMS[$i + 5] }}</td>
                    @php
                        $totalSampleSTR += $strFwdToAFIMS[$i];
                        $totalBatchSTR += $strFwdToAFIMS[$i + 5];
                    @endphp
                @endfor
                <td style="border: 2px solid black; text-align: center;" id="totalSTRSample">{{ $totalSampleSTR }}</td>
                <td style="border: 2px solid black; text-align: center;" id="totalSTRBatch">{{ $totalBatchSTR }}</td>
            </tr>
            <tr id="pending">
              
            </tr>
        </tbody>
    
    </table> --}}

    <div class="row mt-5">
        <div class="col-md-12">
            <h4 style="text-decoration: underline;text-align:center;margin-top:40px" ><b>Tender Samples Details</b></h4>
        </div>
        <div class="col-md-12">
            <table class="table table-bordered" id="allTran" sborder="2px solid black" style="text-align: center">
                <thead class="text-center">
                </thead>
                <tbody>
    
                    <tr>
                        <td  style="border: 2px solid black; text-align: center;" colspan="2"></td>
                        <td  style="border: 2px solid black; text-align: center;">T/E</td>
                        <td  style="border: 2px solid black; text-align: center;">Firms/Batches</td>
                      
                    </tr>
                    <tr>
                        <td  style="border: 2px solid black; text-align: center;" rowspan="4">Total No. Of Samples</td>
                    </tr>
    
                    <tr>
                        <td  style="border: 2px solid black; text-align: center;">Received from AFIMS</td>
                        <td  style="border: 2px solid black; text-align: center;">{{ $TotalSTRSamples }}</td>
                        <td  style="border: 2px solid black; text-align: center;">{{ $TotalReceivedBatchs }}</td>
                      
                    </tr>
                    <tr>
                        <td  style="border: 2px solid black; text-align: center;">STR Fwd to AFIMS</td>                          
                        <td  style="border: 2px solid black; text-align: center;">52(-)</td>
                        <td  style="border: 2px solid black; text-align: center;">74(-)</td>
                    </tr>
                    <tr>
                        <td  style="border: 2px solid black; text-align: center;">Total Pending</td>
                        <td  style="border: 2px solid black; text-align: center;">05</td>
                        <td  style="border: 2px solid black; text-align: center;">05</td>
                    </tr>
                </tbody>
    
            </table>
        </div>
    </div>
    @endcomponent
</section>
<script src="{{ asset('js/home.js?v=' . $asset_v) }}"></script>

@endsection